account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from account.views import signup

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("account.urls")),
    path("receipts/", include("receipt.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipt/urls.py
from django.urls import path

from receipt.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountsListView,
    AccountsCreateView,
    ExpensesListView,
    ExpensesCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("accounts/list/", AccountsListView.as_view(), name="list_account"),
    path(
        "accounts/create/", AccountsCreateView.as_view(), name="create_account"
    ),
    path(
        "categories/list/",
        ExpensesListView.as_view(),
        name="list_expense",
    ),
    path(
        "categories/create/",
        ExpensesCreateView.as_view(),
        name="create_expense",
    ),
]

account/models.py
from django.db import models

# Create your models here.

receipt/models.py
from django.db import models
from django.conf import settings


class Expenses(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="expense",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.name)


class Accounts(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="account",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return str(self.name)


class Receipts(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=False,
        related_name="receipt",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "Expenses",
        null=True,
        related_name="receipt",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Accounts",
        null=True,
        related_name="receipt",
        on_delete=models.CASCADE,
    )

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# needs a def fun. not a class.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signups.html", context)

receipt/views.py
from django.shortcuts import redirect
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from receipt.models import Accounts, Expenses, Receipts


class AccountsCreateView(LoginRequiredMixin, CreateView):
    model = Accounts
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_account")


class AccountsListView(LoginRequiredMixin, ListView):
    model = Accounts
    template_name = "accounts/list.html"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_account")


class ExpensesCreateView(LoginRequiredMixin, CreateView):
    model = Expenses
    template_name = "expense_categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_expense")


class ExpensesListView(ListView):
    model = Expenses
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return Expenses.objects.filter(owner=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipts
    template_name = "receipt/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")


class ReceiptListView(ListView):
    model = Receipts
    template_name = "receipt/list.html"

    def get_queryset(self):
        return Receipts.objects.filter(purchaser=self.request.user)


# Create your views here.

# Create your views here.
# List views
# class ModelNameListView(ListView):
#     model = ModelName
#     template_name = "model_names/list.html"

# # Detail views
# class ModelNameDetailView(DetailView):
#     model = ModelName
#     template_name = "model_names/detail.html"

# Create views
# class ModelNameCreateView(CreateView):
#     model = ModelName
#     template_name = "model_names/create.html"
#     fields = ["model", "properties", "for", "your", "form"]

#     # Redirects to the detail page for the
#     # instance just created, assuming that
#     # the path name is registered
#     def get_success_url(self):
#         return reverse_lazy("model_name_detail", args=[self.object.id])

# Update views
# class ModelNameUpdateView(UpdateView):
#     model = ModelName
#     template_name = "model_names/update.html"
#     fields = ["model", "properties", "for", "your", "form"]

#     # Redirects to the detail page for the
#     # instance just created, assuming that
#     # the path name is registered
#     def get_success_url(self):
#         return reverse_lazy("model_name_detail", args=[self.object.id])

# Update views
# class ModelNameUpdateView(UpdateView):
#     model = ModelName
#     template_name = "model_names/update.html"
#     fields = ["model", "properties", "for", "your", "form"]

#     # Redirects to the detail page for the
#     # instance just created, assuming that
#     # the path name is registered
#     def get_success_url(self):
#         return reverse_lazy("model_name_detail", args=[self.object.id])

receipt/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
<div class="narrow-form">
    <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
</div>
{% endblock content %}

receipt/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Accounts</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for account in accounts_list %}
        <tr>
            <td>{{ account.name }}</td>
            <th>{{ account.number }}</td>
            <td>{{ account.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <title>Me Receipts</title>
</head>

<body>
    <header>
        <nav>
            <ul class="navigation">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'home' %}">Receipts</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'create_receipt' %}">Create receipt</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'list_account' %}">Accounts</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'create_account' %}">Create account</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'list_expense' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'create_expense' %}">Create category</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>

</html>
<!-- <h1>a working base html page</h1> -->

receipt/templates/expense_categories/create.html
{% extends 'base.html' %}

{% block content %}
<div class="narrow-form">
    <h1>Create Expenses Category</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
</div>
{% endblock content %}

receipt/templates/expense_categories/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Expense Categories</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for category in expenses_list %}
        <tr>
            <td>{{ category.name }}</td>
            <td>{{ category.receipt.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipt/templates/receipt/create.html
{% extends 'base.html' %}

{% block content %}
<div class="narrow-form">
    <h1>Create Receipt</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create</button>
    </form>
</div>
{% endblock content %}

receipt/templates/receipt/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Receipts</h1>
<table>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for receipt in receipts_list %}
        <tr>
            <td>{{ receipt.vendor }}</td>
            <td>{{ receipt.total }}</td>
            <td>{{ receipt.tax }}</td>
            <td>{{ receipt.date|date:"m-d-Y" }}</td>
            <td>{{ receipt.category }}</td>
            <td>{{ receipt.account }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}
<!-- <h1>a working list html page</h1> -->